[project]
name = "d2l-recurrence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beartype>=0.20.2",
    "d2l==0.17.6",
    "scipy>=1.10.1",
    "torch==1.12.0",
    "torchtyping>=0.1.5",
    "torchvision==0.13.0",
]
